# Generated by Django 3.2.14 on 2022-11-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('audio_file', models.FileField(upload_to='media_audio/')),
                ('description', models.TextField(max_length=550)),
                ('clue1', models.CharField(max_length=200)),
                ('clue2', models.CharField(max_length=200)),
                ('clue3', models.CharField(max_length=200)),
                ('clue4', models.CharField(max_length=200)),
                ('answer_option1', models.CharField(max_length=200)),
                ('answer_option2', models.CharField(max_length=200)),
                ('answer_option3', models.CharField(max_length=200)),
                ('answer_option4', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
    ]
